#!/bin/bash

# change to directory of the script
cd "$(dirname "$0")"

# load username from .username file, promt if not provided
FILE=.username
if [ -f "$FILE" ]; then
    username="$(cat $FILE)"
else
    echo "$FILE existiert nicht!"
    read -p "username für Pool eingeben: "  username
    echo $username >> $FILE
fi

# set workdir
dir="/data/scratch/wuerfel/ieee-rts-96_workdir"

echo "Connect to pool$poolnr as $username"
# create workdid if needed
ssh ${username}@pool.physik.hu-berlin.de mkdir -p ${dir}

echo "Syinc files to pool: $dir"
rsync -zP --recursive --exclude="results" --exclude="Literature" --exclude=".git" --delete . ${username}@pool.physik.hu-berlin.de:${dir}
